version: 2

# Publish only changes pushed to `master` branch.
general:
  branches:
    only:
      - master

jobs:
  build:
    docker:
      # Set build environment to use same docker image as local docker-compose
      - image: jguyomard/hugo-builder:0.32

    working_directory: ~/code

    steps:
      # Inject created SSH key into container
      - add_ssh_keys:
        fingerprints:
          - "ff:d6:2a:ea:37:31:08:01:e0:40:2a:e7:25:24:99:3c"

      # Configure git to be able to push
      - run: git config --global user.email bot@friederikewild.me
      - run: git config --global user.name CircleCI

      # Checkout source code
      - checkout

      # Run publish script :-)
      - run: .circleci/publish_to_ghpages
