#!/bin/sh

set -e

#if [[ $(git status -s) ]]
#then
#    echo "The working directory is dirty. Please commit any pending changes."
#    exit 1;



PUBLIC="public"

if [[ $FOLDER ]]; then
	DIR=$FOLDER$PUBLIC
else
	DIR="../"$PUBLIC
fi


echo "Using folder $PUBLIC"


echo "Deleting old publication"
rm -rf $PUBLIC
mkdir $PUBLIC
git worktree prune
rm -rf .git/worktrees/$PUBLIC/

echo "Checking out gh-pages branch into public"
git worktree add -B gh-pages $PUBLIC origin/gh-pages


echo "Removing existing files"
rm -rf $PUBLIC/*

echo "Generating site"
hugo


timestamp=$(date +%s%3N)

echo "Updating gh-pages branch"
if [[ $CI ]]; then
  message="* [CI] Publishing to gh-pages $timestamp"
else
  message="* Publishing to gh-pages $timestamp"
fi

echo "Publishing version $timestamp"
cd $PUBLIC && \
  git add --all && \
  git commit -m "$message" && \
  git tag "$timestamp" && \
  git push origin gh-pages && \
  git push origin "$timestamp"

echo "Published version $timestamp"
